cbv/app_one/urls.py
from django.urls import path
from app_one import views

app_name = 'app_one'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),
]

cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from app_one import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.indexView.as_view()),
    path('app_one/',include('app_one.urls',namespace='app_one')),
]

cbv/app_one/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("app_one:detail", kwargs = {'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

cbv/app_one/views.py
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView
from app_one import models
from django.urls import reverse_lazy

# Create your views here.

class indexView(TemplateView):
    template_name='index.html'

    # def get_context_data(self,**kwargs):
    #     context=super().get_context_data(**kwargs)
    #     context['injectme']='hey deer im being injected!!!'
    #     return context

class SchoolListView(ListView):
    model = models.School
    context_object_name = 'schools'

class SchoolDetailView(DetailView):
    model = models.School
    template_name = 'app_one/school_detail.html'

    context_object_name = 'school_detail'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('app_one:list')

cbv/app_one/templates/app_one/app_one_base.html
<!DOCTYPE html>
<html>
<head>
    <title>Class Based View</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container navbar-nav">
        <a class="nav-brand" href="{% url 'app_one:list' %}">School</a>
        <a class="nav-list" href="{% url 'admin:index' %}">Admin</a>
    </div>

</nav>


<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

cbv/app_one/templates/app_one/school_confirm_delete.html
{% extends 'app_one/app_one_base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Are you sure, you want to delete {{ school.name }}</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'app_one:detail' pk=school.pk %}" class="btn btn-primary">Cancel</a>
    </form>

</div>
{% endblock %}

cbv/app_one/templates/app_one/school_detail.html
{% extends 'app_one/app_one_base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>This is School detail page</h1>
    <h2>School Details: </h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <h3>Students: </h3>
     <ol>
    {% for student in school_detail.students.all %}

        <p><li>Name: {{ student.name }}</li></p>
    <p>Age: {{ student.age }}</p>
    {% endfor %}
     </ol>
<br>
    <a class="btn btn-warning" href="{% url 'app_one:update' pk=school_detail.pk %}">Update</a>
    <a class="btn btn-danger" href="{% url 'app_one:delete' pk=school_detail.pk %}">Delete</a>
</div>

{% endblock %}

cbv/app_one/templates/app_one/school_form.html
{% extends 'app_one/app_one_base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
</div>
{% endblock %}

cbv/app_one/templates/app_one/school_list.html
{% extends 'app_one/app_one_base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>This is the list of all the schools</h1>

<ol>
    {% for school in schools %}
    <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
    {% endfor %}
</ol>
    <br>
    <a class="btn btn-primary" href="{% url 'app_one:create' %}">Create School</a>
</div>
{% endblock %}

cbv/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Class Based View</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container navbar-nav">
        <a class="nav-brand" href="{% url 'app_one:list' %}">School</a>
        <a class="nav-list" href="{% url 'admin:index' %}">Admin</a>
    </div>

</nav>


<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

cbv/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>This is an index page!!</h1>
</div>
{% endblock %}